//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.AsignacionVisita = new HashSet<AsignacionVisita>();
            this.Usuario = new HashSet<Usuario>();
            this.HORARIOS = new HashSet<HORARIOS>();
        }
    
        public string apellido { get; set; }
        public Nullable<int> codigoValuacion { get; set; }
        public string cuit { get; set; }
        public Nullable<int> dni { get; set; }
        public string calle { get; set; }
        public Nullable<int> numeroCalle { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string mail { get; set; }
        public string nombre { get; set; }
        public Nullable<int> idSexo { get; set; }
        public Nullable<int> telefono { get; set; }
        public Nullable<int> cargo { get; set; }
        public Nullable<int> idSede { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionVisita> AsignacionVisita { get; set; }
        public virtual Cargo Cargo1 { get; set; }
        public virtual Sede Sede { get; set; }
        public virtual Sexos Sexos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HORARIOS> HORARIOS { get; set; }

        public bool mostrarCargo()
        {
            return this.Cargo1.esGuia();
        }

        public bool trabajaDentroDiaYHorario(int horaReserva, DateTime fechaReserva)
        {
            foreach (var horario in this.HORARIOS)
            {
                if (horario.trabajaDentroDiaYHorario(horaReserva, fechaReserva))
                {
                    return true;
                    
                }
            }
            return false;
        }

        public bool tieneAsignacionParaDiaYHora(int horaReserva, DateTime fechaReserva, int duracion)
        {
            foreach (var asignacion in AsignacionVisita)
            {
                if (asignacion.getDatosFechaHora(horaReserva, fechaReserva, this, duracion))
                {
                    return true;
                }
            }
            return false;
        }

        public Empleado getDatosEmpleado()
        {
            return this;
        }
    }
}
