//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Obra()
        {
            this.DetalleExposicion = new HashSet<DetalleExposicion>();
        }
    
        public Nullable<int> alto { get; set; }
        public Nullable<int> ancho { get; set; }
        public Nullable<int> codigoSensor { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> duracionExtenida { get; set; }
        public Nullable<int> duracionResumida { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaPrimerIngreso { get; set; }
        public string nombreObra { get; set; }
        public Nullable<int> peso { get; set; }
        public Nullable<int> valuacion { get; set; }
        public int idObra { get; set; }
        public Nullable<int> idExposicion { get; set; }
        public Nullable<int> idSede { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleExposicion> DetalleExposicion { get; set; }
        public virtual Exposicion Exposicion { get; set; }
        public virtual Valuaciones Valuaciones { get; set; }

        public double mostrarDuracionExtendida()
        {
            return this.duracionExtenida.Value;
        }
    }
}
