//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionVisita
    {
        public System.DateTime fechaHoraFin { get; set; }
        public string guiaAsignado { get; set; }
        public System.DateTime fechaHoraInicio { get; set; }
        public int idReserva { get; set; }
        public int idSede { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual ReservaVisita ReservaVisita { get; set; }
    }
}
