//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPAIEntities : DbContext
    {
        public PPAIEntities()
            : base("name=PPAIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AsignacionVisita> AsignacionVisita { get; set; }
        public virtual DbSet<CambioEstado> CambioEstado { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<DetalleExposicion> DetalleExposicion { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Escuela> Escuela { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Exposicion> Exposicion { get; set; }
        public virtual DbSet<ExposicionesXSede> ExposicionesXSede { get; set; }
        public virtual DbSet<HORARIOS> HORARIOS { get; set; }
        public virtual DbSet<Obra> Obra { get; set; }
        public virtual DbSet<PublicoDestino> PublicoDestino { get; set; }
        public virtual DbSet<ReservasXSede> ReservasXSede { get; set; }
        public virtual DbSet<ReservaVisita> ReservaVisita { get; set; }
        public virtual DbSet<Sede> Sede { get; set; }
        public virtual DbSet<Sesion> Sesion { get; set; }
        public virtual DbSet<Sexos> Sexos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoExposicion> TipoExposicion { get; set; }
        public virtual DbSet<TipoVisita> TipoVisita { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Valuaciones> Valuaciones { get; set; }
    }
}
