//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleExposicion
    {
        public string lugarAsignado { get; set; }
        public int idObra { get; set; }
        public int idExposicion { get; set; }
        public int idSede { get; set; }
    
        public virtual Obra Obra { get; set; }
        public virtual Exposicion Exposicion { get; set; }
    }
}
