//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escuela
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Escuela()
        {
            this.ReservaVisita = new HashSet<ReservaVisita>();
        }
    
        public string calle { get; set; }
        public Nullable<int> numeroCalle { get; set; }
        public string mail { get; set; }
        public string nombre { get; set; }
        public Nullable<int> telefCelular { get; set; }
        public Nullable<int> telefFijo { get; set; }
        public int idEscuela { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservaVisita> ReservaVisita { get; set; }

        internal Escuela getEscuela()
        {
            return this;
        }
    }
}
