//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exposicion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exposicion()
        {
            this.DetalleExposicion = new HashSet<DetalleExposicion>();
            this.Obra = new HashSet<Obra>();
            this.PublicoDestino2 = new HashSet<PublicoDestino>();
        }
    
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<System.DateTime> fechaFinReplanificada { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaInicioReplanificada { get; set; }
        public Nullable<System.TimeSpan> horaApertura { get; set; }
        public Nullable<System.TimeSpan> horaCierre { get; set; }
        public string nombre { get; set; }
        public int idExposicion { get; set; }
        public int idSede { get; set; }
        public Nullable<int> idTipoExposicion { get; set; }
        public Nullable<int> publicoDestino { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleExposicion> DetalleExposicion { get; set; }
        public virtual PublicoDestino PublicoDestino1 { get; set; }
        public virtual Sede Sede { get; set; }
        public virtual ExposicionesXSede ExposicionesXSede { get; set; }
        public virtual TipoExposicion TipoExposicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obra> Obra { get; set; }

        internal string mostrarHorarioApertura()
        {
            return horaApertura.ToString();
        }

        internal string mostrarHorarioCierre()
        {
            return horaCierre.ToString();
        }
        /// <summary>
        ///
        /// </summary>
        /// <returns>Devuelve una lista que tiene como primer elemento 
        /// el nombre de la exposicion y luego los nombres de los publicos de destino</returns>
        public List<string> buscarExposicionesTemporales()
        {
            List<string> nombresPublicos = new List<string>();
            nombresPublicos.Add(nombre);
            if (TipoExposicion.esTemporal())
            {
                foreach (PublicoDestino publico in PublicoDestino2)
                {
                    string nombre = publico.mostrarNombre();
                    nombresPublicos.Add(nombre);
                }
            }
            return nombresPublicos;
        }

        internal bool esVigente()
        {
            throw new NotImplementedException();
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublicoDestino> PublicoDestino2 { get; set; }
    }
}
