//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservaVisita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReservaVisita()
        {
            this.AsignacionVisita = new HashSet<AsignacionVisita>();
        }
    
        public Nullable<int> cantidadAlumno { get; set; }
        public Nullable<int> cantidadAlumnoConfirmada { get; set; }
        public Nullable<int> duracionEstimada { get; set; }
        public Nullable<System.DateTime> fechaHoraCreacion { get; set; }
        public Nullable<System.DateTime> fechaHoraReserva { get; set; }
        public Nullable<System.TimeSpan> horaFinReal { get; set; }
        public Nullable<System.TimeSpan> horaInicioReal { get; set; }
        public int idReserva { get; set; }
        public int idSede { get; set; }
        public Nullable<int> idEscuela { get; set; }
        public Nullable<System.DateTime> fechaHoraInicio { get; set; }
        public Nullable<int> ordId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionVisita> AsignacionVisita { get; set; }
        public virtual CambioEstado CambioEstado { get; set; }
        public virtual Escuela Escuela { get; set; }
        public virtual ReservasXSede ReservasXSede { get; set; }
        public virtual Sede Sede { get; set; }
    }
}
