//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sesion
    {
        public Nullable<System.DateTime> fechaYHoraFin { get; set; }
        public int idUsuario { get; set; }
        public System.DateTime fechaYHoraInicio { get; set; }
    
        public virtual Usuario Usuario { get; set; }

        internal Empleado buscarEmpleadoEnSesion()
        {
            return Usuario.buscarEmpleadoEnSesion();
        }
    }
}
