//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionVisita
    {
        public System.DateTime fechaHoraFin { get; set; }
        public string guiaAsignado { get; set; }
        public System.DateTime fechaHoraInicio { get; set; }
        public int idReserva { get; set; }
        public int idSede { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual ReservaVisita ReservaVisita { get; set; }


        public bool getDatosFechaHora(int horaReserva, DateTime fechaReserva, Empleado guia, int duracion)
        {
            List<AsignacionVisita> asignaciones = new List<AsignacionVisita>();
            duracion = duracion / 60;

            if (guiaAsignado == guia.cuit &&
                horaReserva >= fechaHoraFin.Hour &&
                (horaReserva + duracion) <= fechaHoraInicio.Hour &&
                fechaHoraInicio.Day == fechaReserva.Day &&
                fechaHoraInicio.Month == fechaReserva.Month &&
                fechaHoraInicio.Year == fechaReserva.Year)
            {
                return false;
            }
            return true;

        }
    }
}
