//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escuela
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Escuela()
        {
            this.ReservaVisita = new HashSet<ReservaVisita>();
        }
    
        public string calle { get; set; }
        public Nullable<int> numeroCalle { get; set; }
        public string mail { get; set; }
        public string nombre { get; set; }
        public Nullable<int> telefCelular { get; set; }
        public Nullable<int> telefFijo { get; set; }
        public int idEscuela { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservaVisita> ReservaVisita { get; set; }

        public string mostrarNombre()
        {
            return nombre;
        }

        public string mostrarId()
        {
            return Convert.ToString(idEscuela);
        }

    }
}
